apiVersion: v1
kind: Service
metadata: # kpt-merge: example/base-app
  name: transactionhistory
  namespace: transactionhistory-dev
  labels:
    app: transactionhistory-dev
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|example|base-app'
spec:
  type: LoadBalancer
  selector:
    app: transactionhistory-dev
  ports:
  - name: http
    port: 80
    targetPort: 8080
