apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: example/environment-config
  name: environment-config
  namespace: userservice-dev
  labels:
    app: userservice
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|example|environment-config'
data:
  LOCAL_ROUTING_NUM: "883745000"
  PUB_KEY_PATH: /tmp/.ssh/publickey
---
apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: example/accounts-db-config
  name: accounts-db-config
  labels:
    app: userservice
  namespace: userservice-dev
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|example|accounts-db-config'
data:
  POSTGRES_DB: accounts-db
  POSTGRES_USER: accounts-admin
  POSTGRES_PASSWORD: accounts-pwd
  ACCOUNTS_DB_URI: postgresql://accounts-admin:accounts-pwd@accounts-db:5432/accounts-db
