apiVersion: v1
kind: Service
metadata: # kpt-merge: example/userservice
  name: userservice
  namespace: userservice-dev
  labels:
    app: userservice
  annotations:
    internal.kpt.dev/upstream-identifier: '|Service|example|userservice'
spec:
  type: ClusterIP
  selector:
    app: userservice
  ports:
  - name: http
    port: 8080
    targetPort: 8080
